# Generated by Django 4.1.4 on 2023-09-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Customer",),
    ]
